services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  mysql-users:
    image: mysql:8
    container_name: mysql-users
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env

  postgres-products:
    image: postgres:15
    container_name: postgres-products
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  mongo-orders:
    image: mongo:6
    container_name: mongo-orders
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env

  postgres-payments:
    image: postgres:15
    container_name: postgres-payments
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env

  gateway:
    build: ./gateway
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    env_file:
      - .env

  users:
    build: ./users
    depends_on:
      - mysql-users
      - rabbitmq
    env_file:
      - .env

  products:
    build: ./products
    depends_on:
      - postgres-products
      - rabbitmq
    env_file:
      - .env

  orders:
    build: ./orders
    depends_on:
      - mongo-orders
      - rabbitmq
    env_file:
      - .env

  payments:
    build: ./payments
    depends_on:
      - postgres-payments
      - rabbitmq
    env_file:
      - .env

  notifications:
    build: ./notifications
    depends_on:
      - rabbitmq
    env_file:
      - .env
